[2016-12-13 13:15:28,492] INFO Bootstrapping AmbryServer (com.github.ambry.server.AmbryMain)
[2016-12-13 13:15:28,503] INFO According to InetAddress.getLocalHost.getHostName we are himrod-8 (com.github.ambry.metrics.JmxServer)
[2016-12-13 13:15:28,749] INFO Started jmx serverJmxServer port= 40223 url= service:jmx:rmi:///jndi/rmi://himrod-8:40223/jmxrmi (com.github.ambry.metrics.JmxServer)
[2016-12-13 13:15:28,752] INFO starting (com.github.ambry.server.AmbryServer)
[2016-12-13 13:15:28,752] INFO Setting up JMX. (com.github.ambry.server.AmbryServer)
[2016-12-13 13:15:28,777] INFO creating configs (com.github.ambry.server.AmbryServer)
[2016-12-13 13:15:28,780] INFO Verifying properties (com.github.ambry.config.VerifiableProperties)
[2016-12-13 13:15:28,781] INFO Property host.name is overridden to localhost (com.github.ambry.config.VerifiableProperties)
[2016-12-13 13:15:28,781] INFO Property store.compaction.hotness.threshold is overridden to 100 (com.github.ambry.config.VerifiableProperties)
[2016-12-13 13:15:28,781] INFO Property store.compaction.threshold is overridden to 0.1 (com.github.ambry.config.VerifiableProperties)
[2016-12-13 13:15:28,782] INFO check if node exist in clustermap host localhost port 6667 (com.github.ambry.server.AmbryServer)
[2016-12-13 13:15:28,786] INFO Starting store manager (com.github.ambry.store.StoreManager)
[2016-12-13 13:15:28,807] INFO Index : /tmp/2 log end offset of index  before recovery 0 (com.github.ambry.store.PersistentIndex)
[2016-12-13 13:15:28,807] INFO Index : /tmp/2 performing recovery on index with start offset 0 and end offset 0 (com.github.ambry.store.PersistentIndex)
[2016-12-13 13:15:28,808] INFO Index : /tmp/2 Starting hard delete recovery (com.github.ambry.store.PersistentIndex)
[2016-12-13 13:15:28,808] INFO Index : /tmp/2 Finished performing hard delete recovery (com.github.ambry.store.PersistentIndex)
[2016-12-13 13:15:28,817] INFO Index : /tmp/0 log end offset of index  before recovery 0 (com.github.ambry.store.PersistentIndex)
[2016-12-13 13:15:28,817] INFO Index : /tmp/0 performing recovery on index with start offset 0 and end offset 0 (com.github.ambry.store.PersistentIndex)
[2016-12-13 13:15:28,818] INFO Index : /tmp/0 Starting hard delete recovery (com.github.ambry.store.PersistentIndex)
[2016-12-13 13:15:28,818] INFO Index : /tmp/0 Finished performing hard delete recovery (com.github.ambry.store.PersistentIndex)
[2016-12-13 13:15:28,823] INFO Index : /tmp/1 log end offset of index  before recovery 0 (com.github.ambry.store.PersistentIndex)
[2016-12-13 13:15:28,824] INFO Index : /tmp/1 performing recovery on index with start offset 0 and end offset 0 (com.github.ambry.store.PersistentIndex)
[2016-12-13 13:15:28,824] INFO Index : /tmp/1 Starting hard delete recovery (com.github.ambry.store.PersistentIndex)
[2016-12-13 13:15:28,824] INFO Index : /tmp/1 Finished performing hard delete recovery (com.github.ambry.store.PersistentIndex)
[2016-12-13 13:15:28,824] INFO Starting store manager complete (com.github.ambry.store.StoreManager)
[2016-12-13 13:15:28,827] INFO BlockingChannelConnectionPool started (com.github.ambry.network.BlockingChannelConnectionPool)
[2016-12-13 13:15:28,835] INFO Reading replica tokens for mount path /tmp (com.github.ambry.replication.ReplicationManager)
[2016-12-13 13:15:28,835] WARN Number of Datacenters to replicate from is 0, not starting any replica threads (com.github.ambry.replication.ReplicationManager)
[2016-12-13 13:15:28,850] INFO Starting 8 processor threads (com.github.ambry.network.SocketServer)
[2016-12-13 13:15:28,855] INFO Starting acceptor threads (com.github.ambry.network.SocketServer)
[2016-12-13 13:15:28,858] INFO Awaiting socket connections on localhost:6667 (com.github.ambry.network.Acceptor)
[2016-12-13 13:15:28,859] INFO Started server (com.github.ambry.network.SocketServer)
[2016-12-13 13:15:28,859] INFO started (com.github.ambry.server.AmbryServer)
[2016-12-13 13:15:28,859] INFO Server startup time in Ms 107 (com.github.ambry.server.AmbryServer)
[2016-12-13 13:15:33,777] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:15:36,716] INFO Creating first segment (com.github.ambry.store.PersistentIndex)
[2016-12-13 13:15:36,965] INFO Creating first segment (com.github.ambry.store.PersistentIndex)
[2016-12-13 13:15:37,242] INFO Creating first segment (com.github.ambry.store.PersistentIndex)
[2016-12-13 13:15:38,765] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:15:43,763] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:15:48,763] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:15:51,537] INFO Store : BEGIN COMPACTION (com.github.ambry.store.BlobStore)
[2016-12-13 13:15:51,861] INFO Store : BEGIN COMPACTION (com.github.ambry.store.BlobStore)
[2016-12-13 13:15:53,251] INFO Store : END COMPACTION (com.github.ambry.store.BlobStore)
Store Partition[2]: Compaction runtime: 1390ms
[2016-12-13 13:15:53,252] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@45c500af (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/2
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:15:53,252] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@8b004f2 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/2
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:15:53,318] INFO Store : END COMPACTION (com.github.ambry.store.BlobStore)
Store Partition[0]: Compaction runtime: 1781ms
[2016-12-13 13:15:53,318] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAAAAAAAJDlkNTMzZGZhLTg3MDAtNDY4OS1iYWI1LTRlYmRkMjFmMGQxMw, ClientId=localhost, CorrelationId=2132] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/0
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:15:53,318] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAAAAAAAJGE3MTk1ZWYzLWQzNDMtNDU1Zi05NWUxLWYyYmVkNWUwMjVkZQ, ClientId=localhost, CorrelationId=2060] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/0
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:15:53,318] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@65c34565 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/0
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:15:53,318] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@34c40ed6 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/0
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:15:53,318] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@33aa1eaa (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/0
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:15:53,755] INFO Store : BEGIN COMPACTION (com.github.ambry.store.BlobStore)
[2016-12-13 13:15:53,759] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:15:55,293] INFO Store : END COMPACTION (com.github.ambry.store.BlobStore)
Store Partition[1]: Compaction runtime: 1538ms
[2016-12-13 13:15:55,293] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@35cee582 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/1
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:15:55,293] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@9856ec1 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/1
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:15:55,293] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAABAAAAJGU5N2JkYTA2LTNkMjQtNGE2OS05OTZjLWVkMjczOWYyNWY3Yw, ClientId=localhost, CorrelationId=2268] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/1
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:15:55,293] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAABAAAAJDU0NjdlZGE3LWQwNzAtNGU0NS05MmMwLTA0NTU0OWM3ZDEzYQ, ClientId=localhost, CorrelationId=2270] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/1
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:15:55,293] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAABAAAAJDE1MTAxYzJlLWM4MjktNDU5NS04OWU4LWY5NDhhYzk3YzFkNA, ClientId=localhost, CorrelationId=2273] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/1
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:15:58,630] ERROR Index : /tmp/0 error while persisting the index to disk  (com.github.ambry.store.PersistentIndex)
com.github.ambry.store.StoreException: SafeEndOffSet 907197130 is greater than current end offset for current index segment 802509256
	at com.github.ambry.store.IndexSegment.writeIndexToFile(IndexSegment.java:472)
	at com.github.ambry.store.PersistentIndex$IndexPersistor.write(PersistentIndex.java:1074)
	at com.github.ambry.store.PersistentIndex$IndexPersistor.run(PersistentIndex.java:1085)
	at com.github.ambry.utils.Scheduler$2.run(Scheduler.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:15:58,761] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:16:00,192] INFO Store : BEGIN COMPACTION (com.github.ambry.store.BlobStore)
[2016-12-13 13:16:01,378] INFO Store : END COMPACTION (com.github.ambry.store.BlobStore)
Store Partition[2]: Compaction runtime: 1186ms
[2016-12-13 13:16:01,378] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@5c7d517 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/2
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:16:01,379] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@31490eab (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/2
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:16:01,379] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAACAAAAJDQ1M2JlOGExLTA3NDYtNDRiYS05NmExLTg0OTAxMmM0MzJmNg, ClientId=localhost, CorrelationId=3091] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/2
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:16:01,379] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@215e3fd1 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/2
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:16:01,379] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@4963780b (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/2
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:16:01,409] INFO Store : BEGIN COMPACTION (com.github.ambry.store.BlobStore)
[2016-12-13 13:16:02,694] INFO Store : END COMPACTION (com.github.ambry.store.BlobStore)
Store Partition[0]: Compaction runtime: 1285ms
[2016-12-13 13:16:02,694] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@a7393a2 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/0
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:16:02,694] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAAAAAAAJGFlMDgyZDc5LTRiNDYtNGQ2MS04OGI2LTE3Y2VmOWYxMjQ5NA, ClientId=localhost, CorrelationId=3166] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/0
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:16:02,694] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@110ca001 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/0
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:16:02,694] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@29e1760a (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/0
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:16:02,694] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAAAAAAAJDllNDQzODBjLTAzZTAtNGEzNC1iNWRiLTJhOTgzYTEwMmRkYQ, ClientId=localhost, CorrelationId=3214] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/0
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:16:03,756] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:16:05,445] INFO Store : BEGIN COMPACTION (com.github.ambry.store.BlobStore)
[2016-12-13 13:16:06,423] INFO Store : END COMPACTION (com.github.ambry.store.BlobStore)
Store Partition[1]: Compaction runtime: 978ms
[2016-12-13 13:16:06,423] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@67cd35c5 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/1
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:16:06,423] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAABAAAAJDAxMzZhYTNiLTU1OWEtNDMwMS05ZmFkLTFhZDE5YjQ0MjI4ZQ, ClientId=localhost, CorrelationId=3731] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/1
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:16:06,423] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@6b3a210 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/1
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:16:06,423] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAABAAAAJDFiMTlhYTBjLTZiZTgtNDUxZC1iMTM1LTk2Y2I2YzRhNWM1YQ, ClientId=localhost, CorrelationId=3748] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/1
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:16:06,423] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@51854dc0 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/1
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:16:08,754] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:16:11,209] INFO Store : BEGIN COMPACTION (com.github.ambry.store.BlobStore)
[2016-12-13 13:16:11,957] INFO Store : END COMPACTION (com.github.ambry.store.BlobStore)
Store Partition[0]: Compaction runtime: 748ms
[2016-12-13 13:16:11,958] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@1b67ed25 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/0
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:16:11,958] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@77e57f16 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/0
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:16:11,958] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@69197dd8 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/0
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:16:11,958] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAAAAAAAJDYzOTlkMmI0LTUzMmQtNDhhMy05MDA1LTUxOTE1YjYxNGFkNg, ClientId=localhost, CorrelationId=4426] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/0
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:16:11,958] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@44022631 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/0
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:16:13,754] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:16:15,892] INFO Store : BEGIN COMPACTION (com.github.ambry.store.BlobStore)
[2016-12-13 13:16:16,537] INFO Store : END COMPACTION (com.github.ambry.store.BlobStore)
Store Partition[2]: Compaction runtime: 645ms
[2016-12-13 13:16:16,537] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@3c94026e (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/2
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:16:16,537] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAACAAAAJDQ3OTZlM2UxLWU0YWQtNGM4NC1iMzAzLWQxODBhYWNhNTNkNg, ClientId=localhost, CorrelationId=5016] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/2
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:16:16,537] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@7fcf1934 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/2
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:16:16,537] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAACAAAAJGYxOGIxNzc5LTBhYWUtNDc2Zi1hYTQ3LTExOGIwODk1Zjg0NA, ClientId=localhost, CorrelationId=4977] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/2
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:16:16,537] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@192ba2d4 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/2
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:16:17,008] INFO Store : BEGIN COMPACTION (com.github.ambry.store.BlobStore)
[2016-12-13 13:16:17,858] INFO Store : END COMPACTION (com.github.ambry.store.BlobStore)
Store Partition[1]: Compaction runtime: 850ms
[2016-12-13 13:16:17,858] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAABAAAAJDMxNTFiN2FiLWI3MDUtNGUwNi05NzU4LTJlMjlhMGVmYmM2Yg, ClientId=localhost, CorrelationId=5155] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/1
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:16:17,858] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@61245c4f (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/1
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:16:17,858] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAABAAAAJDg0MzFmNjhhLTY0ZWUtNGIxMi04YmJhLTRlN2IwM2RmNzZmNw, ClientId=localhost, CorrelationId=5132] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/1
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:16:17,858] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAABAAAAJGMzY2JlOWUxLTVhZmUtNDE5NS1hYmZiLWRiODA5NzRkODRmMA, ClientId=localhost, CorrelationId=5149] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/1
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:16:17,858] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@2b4b5e6d (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/1
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:16:18,755] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:16:23,434] INFO Store : BEGIN COMPACTION (com.github.ambry.store.BlobStore)
[2016-12-13 13:16:23,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:16:24,030] INFO Store : END COMPACTION (com.github.ambry.store.BlobStore)
Store Partition[0]: Compaction runtime: 596ms
[2016-12-13 13:16:24,030] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@ef28a30 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/0
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:16:24,030] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAAAAAAAJDdjYTRkZWI0LTA1ZjEtNDY1Zi1hM2U0LTQ0YTZlZmNmNGI2Yw, ClientId=localhost, CorrelationId=5868] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/0
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:16:24,030] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAAAAAAAJGZjYmM1MDJjLTMwOTQtNGEyZC05NWI4LWE0ZTFkNWY5MDQzOQ, ClientId=localhost, CorrelationId=5866] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/0
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:16:24,030] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@554e5cfa (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/0
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:16:24,030] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAAAAAAAJDcwZTVmZGM5LTZmYzQtNDhhOS1hYzA2LTQ3YzE1OTdjOTJhOQ, ClientId=localhost, CorrelationId=5890] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/0
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:16:27,835] INFO Store : BEGIN COMPACTION (com.github.ambry.store.BlobStore)
[2016-12-13 13:16:28,330] INFO Store : END COMPACTION (com.github.ambry.store.BlobStore)
Store Partition[2]: Compaction runtime: 495ms
[2016-12-13 13:16:28,330] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAACAAAAJDIxZmY3OTgyLTA5YzktNDFlYi1iNTAxLTVmMWQ3YzMzZGE3ZQ, ClientId=localhost, CorrelationId=6430] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/2
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:16:28,330] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@6f0ee75a (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/2
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:16:28,754] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:16:31,114] INFO Store : BEGIN COMPACTION (com.github.ambry.store.BlobStore)
[2016-12-13 13:16:31,606] INFO Store : END COMPACTION (com.github.ambry.store.BlobStore)
Store Partition[1]: Compaction runtime: 492ms
[2016-12-13 13:16:31,606] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@3ced6dee (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/1
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:16:31,606] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@616d071a (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/1
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:16:31,606] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAABAAAAJDQ3NzNhMTYyLWIxNTUtNGQwOS04YTQ0LWZhNTVlZGFiZTUxZQ, ClientId=localhost, CorrelationId=6774] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/1
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:16:31,606] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@7cc4382 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/1
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:16:31,606] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@3ced6dee (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/1
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:16:33,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:16:37,691] INFO Store : BEGIN COMPACTION (com.github.ambry.store.BlobStore)
[2016-12-13 13:16:38,526] INFO Store : END COMPACTION (com.github.ambry.store.BlobStore)
Store Partition[0]: Compaction runtime: 835ms
[2016-12-13 13:16:38,527] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@2426e26f (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/0
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:16:38,527] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAAAAAAAJDc5MzU5ZmFlLWM0M2QtNDg3YS05ZDJiLWI2Zjc4ODFlZDM0Mw, ClientId=localhost, CorrelationId=7598] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/0
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:16:38,527] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@74dbf7f3 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/0
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:16:38,527] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAAAAAAAJDc5NGI5MmJlLTNhZTEtNDc1YS04NGYwLTY2ZTJhZGY3MzgxOA, ClientId=localhost, CorrelationId=7620] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/0
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:16:38,527] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAAAAAAAJDE1NGUzYjhlLWFlYzItNDI0Ni04YTc0LWJiODk5MGNlMzg3ZQ, ClientId=localhost, CorrelationId=7622] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/0
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:16:38,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:16:43,308] INFO Store : BEGIN COMPACTION (com.github.ambry.store.BlobStore)
[2016-12-13 13:16:43,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:16:43,845] INFO Store : END COMPACTION (com.github.ambry.store.BlobStore)
Store Partition[2]: Compaction runtime: 536ms
[2016-12-13 13:16:43,845] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@4093d9c7 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/2
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:16:43,845] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAACAAAAJDdlOGNiNDdkLWJlMDItNGRlMy1iMWY3LWI2MmRmYjZhMzgwNg, ClientId=localhost, CorrelationId=8254] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/2
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:16:43,845] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@2abeb8f0 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/2
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:16:44,146] INFO Store : BEGIN COMPACTION (com.github.ambry.store.BlobStore)
[2016-12-13 13:16:44,571] INFO Store : END COMPACTION (com.github.ambry.store.BlobStore)
Store Partition[1]: Compaction runtime: 425ms
[2016-12-13 13:16:44,571] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAABAAAAJDY4NDUxNDhhLWI3ODgtNGY2Zi05ZjRlLWUwNjc2ZDYxYmY3Mw, ClientId=localhost, CorrelationId=8367] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/1
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:16:44,571] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAABAAAAJDU1Y2M5M2M1LTM3ZGYtNDRhNC05NDI5LTE0OTA0NWQ0MDZmNA, ClientId=localhost, CorrelationId=8342] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/1
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:16:44,571] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@53753747 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/1
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:16:44,571] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAABAAAAJGMzMTg2NDA3LWViN2QtNDRjZi1iNzBjLTZhOGQ0NmVkMTRiOA, ClientId=localhost, CorrelationId=8365] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/1
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:16:48,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:16:53,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:16:58,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:17:02,581] INFO Store : BEGIN COMPACTION (com.github.ambry.store.BlobStore)
[2016-12-13 13:17:02,931] INFO Store : END COMPACTION (com.github.ambry.store.BlobStore)
Store Partition[2]: Compaction runtime: 350ms
[2016-12-13 13:17:02,931] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@50b873b8 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/2
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:17:02,932] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@7db55e6e (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/2
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:17:02,931] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAACAAAAJDZjMmVmZjk5LWVkOTMtNGJmNy04OWVmLTAzZDc4YzE4ZTZlMg, ClientId=localhost, CorrelationId=10557] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/2
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:17:02,931] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAACAAAAJDllMDI5OTY0LTcwYTktNDRlOS1iYzQ3LWQzNzljYTAyNGYwYg, ClientId=localhost, CorrelationId=10559] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/2
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:17:03,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:17:05,104] INFO Store : BEGIN COMPACTION (com.github.ambry.store.BlobStore)
[2016-12-13 13:17:05,691] INFO Store : END COMPACTION (com.github.ambry.store.BlobStore)
Store Partition[1]: Compaction runtime: 587ms
[2016-12-13 13:17:05,691] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@7cfbe064 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/1
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:17:05,691] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAABAAAAJDRkYjc0MGRkLTM0MTAtNDQyMy1iMzI1LTVkYmE4YjcwNWQyZA, ClientId=localhost, CorrelationId=10814] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/1
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:17:05,691] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@7230a5f0 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/1
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:17:05,691] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAABAAAAJDJiM2ZlNjJjLTkxNWUtNDYxNS04M2RhLWQwODIyMzM1NGQ2Yg, ClientId=localhost, CorrelationId=10822] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/1
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:17:05,691] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@7c490556 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/1
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:17:06,654] INFO Store : BEGIN COMPACTION (com.github.ambry.store.BlobStore)
[2016-12-13 13:17:07,044] INFO Store : END COMPACTION (com.github.ambry.store.BlobStore)
Store Partition[0]: Compaction runtime: 390ms
[2016-12-13 13:17:07,044] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@79c1a0cb (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/0
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:17:07,045] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@72acd989 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/0
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:17:07,044] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@276c58fe (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/0
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:17:07,044] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@1723ade0 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/0
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:17:07,045] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@159d5cf4 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/0
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:17:08,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:17:13,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:17:18,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:17:22,983] INFO Store : BEGIN COMPACTION (com.github.ambry.store.BlobStore)
[2016-12-13 13:17:23,557] INFO Store : END COMPACTION (com.github.ambry.store.BlobStore)
Store Partition[2]: Compaction runtime: 574ms
[2016-12-13 13:17:23,557] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAACAAAAJGY5ZDIyNGZhLTdjOGMtNDk1MS05ZDBlLThiYmVhNTk1YTUxYw, ClientId=localhost, CorrelationId=12960] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/2
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:17:23,558] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@1488968a (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/2
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:17:23,558] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAACAAAAJDcxYzEzODE2LWQzNDctNDU4NS04NzBkLTU5ZDRiMTZjMjdkMg, ClientId=localhost, CorrelationId=12910] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/2
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:17:23,558] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@3b6f7d42 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/2
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:17:23,558] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@70a6620d (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/2
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:17:23,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:17:28,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:17:28,916] INFO Store : BEGIN COMPACTION (com.github.ambry.store.BlobStore)
[2016-12-13 13:17:29,217] INFO Store : END COMPACTION (com.github.ambry.store.BlobStore)
Store Partition[1]: Compaction runtime: 301ms
[2016-12-13 13:17:29,217] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAABAAAAJDk0NmM4NGZlLTI2OTEtNGNhMC04ZmRkLTFkOTYzZWZjYzY4MA, ClientId=localhost, CorrelationId=13623] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/1
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:17:29,217] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAABAAAAJDAyYTBkMTdhLTE5OTgtNDcxZC05YjEwLTIzY2M3YzUwZDE0ZQ, ClientId=localhost, CorrelationId=13613] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/1
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:17:29,217] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@7e7615fe (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/1
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:17:33,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:17:35,656] INFO Store : BEGIN COMPACTION (com.github.ambry.store.BlobStore)
[2016-12-13 13:17:35,983] INFO Store : END COMPACTION (com.github.ambry.store.BlobStore)
Store Partition[0]: Compaction runtime: 327ms
[2016-12-13 13:17:35,983] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAAAAAAAJDdjZDJmY2E0LTQwZTUtNGEyMC1hMjBmLWVjNzU1ZDJiZjZiZQ, ClientId=localhost, CorrelationId=14420] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/0
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:17:35,983] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAAAAAAAJDc4MTE0ZjU3LTViMjMtNDdlOC04ZjI5LTkxMGQwYmFlNTg1Mw, ClientId=localhost, CorrelationId=14392] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/0
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:17:38,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:17:43,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:17:47,343] INFO Store : BEGIN COMPACTION (com.github.ambry.store.BlobStore)
[2016-12-13 13:17:47,568] INFO Store : END COMPACTION (com.github.ambry.store.BlobStore)
Store Partition[2]: Compaction runtime: 225ms
[2016-12-13 13:17:47,568] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAACAAAAJDI2NTU0NGI5LTkyYTYtNDBkMi04MjNkLTFhOTRmY2Y4YzVlMQ, ClientId=localhost, CorrelationId=15736] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/2
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:17:47,568] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAACAAAAJGRlZDZjOTNkLThlZDItNDljMy1iNWQ3LTIxYTE4OTdjMzFhNQ, ClientId=localhost, CorrelationId=15735] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/2
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:17:48,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:17:53,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:17:58,754] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:18:03,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:18:05,950] INFO Store : BEGIN COMPACTION (com.github.ambry.store.BlobStore)
[2016-12-13 13:18:06,222] INFO Store : END COMPACTION (com.github.ambry.store.BlobStore)
Store Partition[1]: Compaction runtime: 272ms
[2016-12-13 13:18:06,222] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAABAAAAJGIxMGZmY2UwLTM2N2UtNDJlNi1iNDI0LTBmZjM5NTk0MTc0MA, ClientId=localhost, CorrelationId=17896] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/1
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:18:08,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:18:09,172] INFO Store : BEGIN COMPACTION (com.github.ambry.store.BlobStore)
[2016-12-13 13:18:09,452] INFO Store : END COMPACTION (com.github.ambry.store.BlobStore)
Store Partition[0]: Compaction runtime: 280ms
[2016-12-13 13:18:09,452] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAAAAAAAJDI4OTAwNzg5LWJmMDgtNGIxMy1iOTAxLTA1NTYwNmI2ODBkMg, ClientId=localhost, CorrelationId=18266] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/0
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:18:09,453] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@2d91483 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/0
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:18:09,453] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@75430472 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/0
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:18:13,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:18:18,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:18:23,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:18:28,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:18:30,969] INFO Store : BEGIN COMPACTION (com.github.ambry.store.BlobStore)
[2016-12-13 13:18:31,209] INFO Store : END COMPACTION (com.github.ambry.store.BlobStore)
Store Partition[2]: Compaction runtime: 240ms
[2016-12-13 13:18:31,210] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@679fa017 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/2
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:18:31,210] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@321bc965 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/2
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:18:31,210] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@8664e41 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/2
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:18:31,210] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@117b3de2 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/2
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:18:31,210] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@20c77b27 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/2
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:18:33,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:18:38,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:18:43,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:18:45,923] INFO Store : BEGIN COMPACTION (com.github.ambry.store.BlobStore)
[2016-12-13 13:18:46,177] INFO Store : END COMPACTION (com.github.ambry.store.BlobStore)
Store Partition[1]: Compaction runtime: 254ms
[2016-12-13 13:18:46,177] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAABAAAAJDA5OTY1Y2ZmLTgwMTYtNGFkMC1hMGE0LWFkNWJmNzA0NjJhYw, ClientId=localhost, CorrelationId=22516] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/1
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:18:46,177] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@2d3acc3f (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/1
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:18:46,177] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@6f37534b (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/1
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:18:48,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:18:53,624] INFO Store : BEGIN COMPACTION (com.github.ambry.store.BlobStore)
[2016-12-13 13:18:53,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:18:53,877] INFO Store : END COMPACTION (com.github.ambry.store.BlobStore)
Store Partition[0]: Compaction runtime: 253ms
[2016-12-13 13:18:53,877] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@1be1efa4 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/0
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:18:53,877] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAAAAAAAJGRkYWIzMjM3LWQ1NDAtNGY3Mi1iZTAxLTJmNjE3MTlmOTA3NA, ClientId=localhost, CorrelationId=23377] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/0
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:18:53,877] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@52d3c86a (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/0
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:18:53,877] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@e3c0649 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/0
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:18:58,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:19:03,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:19:08,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:19:13,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:19:16,560] INFO Store : BEGIN COMPACTION (com.github.ambry.store.BlobStore)
[2016-12-13 13:19:16,714] INFO Store : END COMPACTION (com.github.ambry.store.BlobStore)
Store Partition[2]: Compaction runtime: 154ms
[2016-12-13 13:19:16,714] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAACAAAAJDUxZGU1YmFjLTBiMTQtNDk3Yy1iY2M3LTRiNWFkNTVjZjRiOQ, ClientId=localhost, CorrelationId=26028] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/2
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:19:16,714] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@2162db22 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/2
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:19:16,714] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@ddb6d85 (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/2
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:19:16,714] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@6120a64d (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/2
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:19:16,714] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@17945ecb (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/2
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:19:18,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:19:23,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:19:28,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:19:33,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:19:38,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:19:43,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:19:46,432] INFO Store : BEGIN COMPACTION (com.github.ambry.store.BlobStore)
[2016-12-13 13:19:46,652] INFO Store : END COMPACTION (com.github.ambry.store.BlobStore)
Store Partition[1]: Compaction runtime: 220ms
[2016-12-13 13:19:46,653] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAABAAAAJDYzNjQyZGEzLTMzMmEtNGYzYi05NzUwLTkyNzNiZmEzOWQxMQ, ClientId=localhost, CorrelationId=29458] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/1
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:19:46,653] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAABAAAAJDAzN2I4Nzg2LWZiYWEtNDZmNy05YjNkLTI0MWZhZDRjM2UzNg, ClientId=localhost, CorrelationId=29468] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/1
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:19:48,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:19:50,397] INFO Store : BEGIN COMPACTION (com.github.ambry.store.BlobStore)
[2016-12-13 13:19:50,634] INFO Store : END COMPACTION (com.github.ambry.store.BlobStore)
Store Partition[0]: Compaction runtime: 237ms
[2016-12-13 13:19:50,634] ERROR Store exception on a put with error code Unknown_Error for request com.github.ambry.protocol.PutRequest$ReceivedPutRequest@7e4c6dcb (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to put blobs to store /tmp/0
	at com.github.ambry.store.BlobStore.put(BlobStore.java:220)
	at com.github.ambry.server.AmbryRequests.handlePutRequest(AmbryRequests.java:168)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:121)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.put(BlobStore.java:193)
	... 4 more
[2016-12-13 13:19:50,634] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAAAAAAAJGZlMTMzZjBmLTg5ODMtNGEzOC04NjY3LTQ4NjA5OTZkMjE5NA, ClientId=localhost, CorrelationId=29910] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/0
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:19:50,634] ERROR Store exception on a delete with error code Unknown_Error for request DeleteRequest[BlobID=AAEAAQAAAAAAAAAAAAAAJDIzYmViZDQ5LWU4ODItNGJkZi1iMzQ3LTAzYzc2MmRhMmJhNQ, ClientId=localhost, CorrelationId=29911] (com.github.ambry.server.AmbryRequests)
com.github.ambry.store.StoreException: Unknown error while trying to delete blobs from store /tmp/0
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:289)
	at com.github.ambry.server.AmbryRequests.handleDeleteRequest(AmbryRequests.java:364)
	at com.github.ambry.server.AmbryRequests.handleRequests(AmbryRequests.java:127)
	at com.github.ambry.server.RequestHandler.run(RequestHandler.java:46)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: File span needs to be positive
	at com.github.ambry.store.FileSpan.<init>(FileSpan.java:25)
	at com.github.ambry.store.BlobStore.delete(BlobStore.java:253)
	... 4 more
[2016-12-13 13:19:53,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-13 13:19:58,753] WARN Error writing to com.github.ambry.clustermap.ClusterMap.localhost-6667-/tmp-ResourceState (com.codahale.metrics.CsvReporter)
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:241)
	at com.codahale.metrics.CsvReporter.reportGauge(CsvReporter.java:234)
	at com.codahale.metrics.CsvReporter.report(CsvReporter.java:150)
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116)
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
